### ISSUE TITLE
跟QQ的SDK冲突，抛出异常

### ISSUE THREAD

**Issue by emilyZhouwm** [steipete/Aspects#106]
用户手机未安装QQ的情况，启动页面式授权，Aspects抛出了异常。

而不用Aspects的工程是没有问题的。

Without the user's mobile phone not installed QQ, opens the page type authorization, raise the abnormal Aspects.Instead of Aspects of the project is no problem.

sdk 地址：

http://wiki.open.qq.com/wiki/mobile/SDK%E4%B8%8B%E8%BD%BD

**Comment by emilyZhouwm** [comment]
![Uploading 3C19A42F-686A-4498-800D-D9D7C834333E.png…]()

**Comment by emilyZhouwm** [comment]
-[TCWebViewController setRequestURLStr:]: unrecognized selector sent to instance 0x156ace060

**Comment by steipete** [comment]
Please use StackOverflow for questions like this. I sadly do not speak Chinese and the URL goes to some Android site.

**Comment by emilyZhouwm** [comment]
![2bb49bf6-1935-46a2-97d0-30b4cfd566fc](https://cloud.githubusercontent.com/assets/6175955/17239287/80577760-5595-11e6-9029-2ac7a36ddc63.png)
