### ISSUE TITLE
how to use in swift 3.0?

### ISSUE THREAD

**Issue by tennysondy** [steipete/Aspects#111]
swift 2.3 can use aspects well, but not work in 3.0

**Comment by CoderTian** [comment]
Me Too， How to solve？

**Comment by CoderTian** [comment]
aspects work well with Swift 3.0 , Maybe the Swift funcation convert OC funcation have been changed, such as 'in' become 'with'

**Comment by iGranDav** [comment]
Here is an example :
```swift
try UIViewController.aspect_hook(#selector(UIViewController.viewDidAppear(_:)),
                                 usingBlock: unsafeBitCast(viewDidAppearCompletionBlock, to: Any.self))
```

I am using the `.PositionAfter` in swift 2.x so `[]` in swift 3. I could add `with: []` in the method or delete it since this is the default value.
