### ISSUE TITLE
Aspects don't intercept the methods of NSMutableString

### ISSUE THREAD

**Issue by ChrislosChen** [steipete/Aspects#124]
NSMutableString *test1 = [[NSMutableString alloc] initWithString:@"abc"];
    NSError *hookError = nil;
    [NSMutableString aspect_hookSelector:@selector(appendString:) withOptions:AspectPositionInstead usingBlock:^(id<AspectInfo> aspectInfo, NSString *aString){
        if (aString.length) {
            NSLog(@"....%@", aString);
        }
        
    } error:&hookError];
    
    if (hookError) {
        NSLog(@"........%@", hookError);
    }
    
    [test1 appendString:@"123123"];
    
    NSLog(@"......%@", test1);

The code above does't work , the log like this as below:

 AOCTest[35714:10671370] ......abc123123

for why, can you help me have a look?

**Comment by steipete** [comment]
You can't hook a class cluster - there are multiple internal hidden classes representing this. It's a bad idea and Aspects is not made for that.

**Comment by ChrislosChen** [comment]
ok, great job, thank u
