### ISSUE TITLE
类方法调用---

### ISSUE THREAD

**Issue by lanchc** [steipete/Aspects#147]
// #import <objc/message.h>
    NSString* nameClass = NSStringFromClass(AspectsViewController.class);
    Class catMetal = objc_getMetaClass([nameClass UTF8String]);
    [catMetal aspect_hookSelector:@selector(hello) withOptions:AspectPositionAfter usingBlock:^(id aspectInfo){
        NSLog(@"hello");
        
    } error:NULL];

**Comment by xindizhiyin2014** [comment]
you can have a look at  https://github.com/xindizhiyin2014/JKUBSAspects, it have the operation of class method hook

**Comment by MRwannian** [comment]
> ```
> // #import <objc/message.h>
> NSString* nameClass = NSStringFromClass(AspectsViewController.class);
> Class catMetal = objc_getMetaClass([nameClass UTF8String]);
> [catMetal aspect_hookSelector:@selector(hello) withOptions:AspectPositionAfter usingBlock:^(id aspectInfo){
>     NSLog(@"hello");
>     
> } error:NULL];
> ```

if use this method, you can not hook  the instance method, it will crash, do you have more solution for hooking class method use Aspects lib, thanks!

**Comment by Assuner-Lee** [comment]
May you can also try Stinger https://github.com/eleme/Stinger

**Comment by xindizhiyin2014** [comment]
thanks，I will try later!

发自我的 iPhone

**Comment by liumenghua** [comment]
> you can have a look at https://github.com/xindizhiyin2014/JKUBSAspects, it have the operation of class method hook

照抄一份加前缀有意思？
