### ISSUE TITLE
Why not recommand aspect for production code ?

### ISSUE THREAD

**Issue by vince-hz** [steipete/Aspects#166]
---
There's known issues with this approach, and to this date (February 2019) I STRICTLY DO NOT RECOMMEND TO USE Aspects IN PRODUCTION CODE. 
---

I found you wrote this in read.me. I'm curious about what is known issues.
Would you mind show some details?

**Comment by Assuner-Lee** [comment]
May you can also try Stinger https://github.com/eleme/Stinger

**Comment by godLoveY** [comment]
您好，邮件已收到
