### ISSUE TITLE
Using Aspects with non-void return types

### ISSUE THREAD

**Issue by cooksimo** [steipete/Aspects#25]
This is not a bug - just a request for clarification:
I am hooking a method where I want to change the return value to something that is created within the block.  I'm having an issue (which is obvious once I see it) where the return value is deallocated as soon as the block completed and hence the calling class causes a crash when it tries to access it.  Here is the example code:

``` obj-c
self.aspectTokenSupportedEvents = [SomeObject aspect_hookSelector:@selector(supportedActions)
    withOptions:AspectPositionInstead
    usingBlock:^(id<AspectInfo> aspectInfo) {
        NSInvocation *invocation = aspectInfo.originalInvocation;
        SomeObject *object = aspectInfo.instance;
        NSArray *arrayOfActions = [object.arrayOfActions mutableCopy];
        CFRetain((__bridge CFTypeRef)(arrayOfActions));
        [invocation setReturnValue:&arrayOfActions];
    }
    error:NULL];
```

Is the `CFRetain` use the correct approach for the situation?

**Comment by luhui** [comment]
Can you tell me why CFRetain+CFAutorelease work? I don't understand.
Retain count of `arrayOFActions` is 2 in both.

I write a test code, but the result is confused to me

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    NSObject *test = [NSObject new];
    
    [test.rac_willDeallocSignal subscribeCompleted:^{
        NSLog(@"test will dealloc");
    }];
    
    NSLog(@"Retain count 1 is %ld", CFGetRetainCount((__bridge CFTypeRef)test));
    
//    CFRetain((__bridge CFTypeRef)test);
    CFRetain(CFAutorelease((__bridge CFTypeRef)test));
    
    NSLog(@"Retain count 2 is %ld", CFGetRetainCount((__bridge CFTypeRef)test));
    
    return YES;
}
```

Use CFRetain, test has not dealloc, but used CFRetain+CFAutorelease, test would be dealloc
