### ISSUE TITLE
Aspects don't intercept the methods of NSFileHandle 

### ISSUE THREAD

**Issue by dhekrazaied** [steipete/Aspects#36]
Hello,
I tried to intercept the methods of NSFileHandle like that :

[NSFileHandle  aspect_hookSelector:@selector(writeData:) withOptions:AspectPositionAfter usingBlock:^(id<AspectInfo> info, NSData *data){
        NSLog(@"writeData: after | object:%@ | instance:%@ | class:%@",info,[info instance],[[info instance] class]);  
    } error:NULL];
    [NSFileHandle aspect_hookSelector:@selector(writeData:) withOptions:AspectPositionBefore usingBlock:^(id<AspectInfo> info, NSString *data){
        NSLog(@"writeData: before | object:%@ | instance:%@ | class:%@",info,[info instance],[[info instance] class]);
    } error:NULL];
  NSString *docPath=[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES)objectAtIndex:0];
    NSString *filePath=[docPath stringByAppendingPathComponent:@"test.json"];
    NSString *resultLine=[NSString stringWithFormat:@"coucou c dhekra"];
    NSString *newFilePath = [NSHomeDirectory()  stringByAppendingPathComponent:@"/Documents/test.json"];
    NSFileHandle *handler = [NSFileHandle fileHandleForUpdatingAtPath:filePath];
    NSLog(@"newFilePath %@ %@",newFilePath,[resultLine dataUsingEncoding:NSUTF8StringEncoding]);
    if(!handler) {
        handler= [NSFileHandle fileHandleForWritingAtPath:newFilePath];
    }
    [handler seekToEndOfFile];
    [handler writeData:[resultLine dataUsingEncoding:NSUTF8StringEncoding]];

 But i didn't have a result why??

**Comment by steipete** [comment]
Things are probably different for toll-free bridged classes or class clusters. Feel free to investigate more. Closing this for now as using aspects for file writing isn't a use case I'd recommend.
