### ISSUE TITLE
Hooking same selector name in different subclasses does not work

### ISSUE THREAD

**Issue by toco** [steipete/Aspects#43]
I'm currently writing an Xcode plugin and got a situation where two classes (IBICMultipartImageSectionTitleView and IBICMultipartImageView) inherit from NSView, don't inherit from each other, but implement the same method name.
I want to hook the selector in both classes individually, but when I try to hook the selector in the second class I get the following error message:
>  Aspects: Error: effectiveTitleColor already hooked in IBICMultipartImageView. A method can only be hooked once per class hierarchy.
> Failed to hook -[IBICMultipartImageSectionTitleView effectiveTitleColor] with error:
> Error Domain=AspectErrorDomain Code=3 "Error: effectiveTitleColor already hooked in IBICMultipartImageView. A method can only be hooked once per class hierarchy." UserInfo=0x600001a6a400 {NSLocalizedDescription=Error: effectiveTitleColor already hooked in IBICMultipartImageView. A method can only be hooked once per class hierarchy.}

I tried to track down the issue and I'm not sure if the following line in ```static BOOL aspect_isSelectorAllowedAndTrack(NSObject *self, SEL selector, AspectOptions options, NSError **error)``` is correct:
https://github.com/steipete/Aspects/blob/3fcc13a27777750fc493bb5d9b9be5f7f369eb91/Aspects.m#L626
Shouldn't the selector name be only added to the tracker of the class for which the implementation is actually hooked?

**Comment by velyan** [comment]
Hi, I have come across an identical problem trying to swizzle loadRequest: method for UIWebView and WKWebView which both inherit UIView.

This has already been mentioned in the documentation as a known limitation:
"An important limitation is that for class-based hooking, a method can only be hooked once within the subclass hierarchy. See #2 This does not apply for objects that are hooked. Aspects creates a dynamic subclass here and has full control."

Is there a work around for this limitation?

Thanks,
V

**Comment by velyan** [comment]
Now I see there is pull request for this. Any idea if / when this is getting merged?
