### ISSUE TITLE
hook "dealloc" crash

### ISSUE THREAD

**Issue by huoyingjie** [steipete/Aspects#49]
[UIResponder aspect_hookSelector:NSSelectorFromString(@"dealloc") withOptions:AspectPositionBefore usingBlock:^(id<AspectInfo> aspectInfo) {
            [[NSNotificationCenter defaultCenter] removeObserver:aspectInfo.instance];
        } error:nil];

add UITextView or UITextField

crash: *** -[UITextInputController dealloc]: message sent to deallocated instance 0x7fec02fc29b0

**Comment by steipete** [comment]
AFAIK doing that is only supported for instances; not globally.

**Comment by huoyingjie** [comment]
I now hook UIResponder dealloc method will UIView, UIImageView, UIButton added to the view, when they were release, the normal procedure. But if you add the UITextView, release, will crash.

**Comment by steipete** [comment]
Apple does a few wicked things in that one... Better not hook.

**Comment by huoyingjie** [comment]
OK，I think it may need other way. Thanks a lot.
