### ISSUE TITLE
how to hook the delegate which don't implements

### ISSUE THREAD

**Issue by l1002k** [steipete/Aspects#52]
when i hook - (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView, i must implement the method, even it's empty method!

**Comment by steipete** [comment]
Yes. Apple checks these methods at the time you set the delegate. Later changes are ignored. Re-set the delegate to work around this.

**Comment by l1002k** [comment]
i mean why not support hook a method which not implement,  add a empty method in aspect.  apple checks these methods when it's called, it don't need to re-set the delegate.
