### ISSUE TITLE
dealloc hooking is broken :(

### ISSUE THREAD

**Issue by fatuhoku** [steipete/Aspects#56]
I just added the following into my `-application:didFinishLaunchingWithOptions:` and nothing showed up when I know for a fact that some `UIViewController`s were in fact deallocated.

``` objc
    [UIViewController aspect_hookSelector:NSSelectorFromString(@"dealloc") withOptions:AspectPositionBefore usingBlock:^(id<AspectInfo> aspectInfo, BOOL animated) {
        NSLog(@"View Controller DEALLOC %@ : %tu", aspectInfo.instance, animated);
    } error:NULL];
```

**Comment by saiday** [comment]
@fatuhoku I using Aspects to monitor UIViewController's dealloc as well, it works flawlessly.

```
    [self.someViewController aspect_hookSelector:NSSelectorFromString(@"dealloc") withOptions:AspectPositionBefore usingBlock:^(id<AspectInfo> aspectInfo) {
        self.beenDealloc = YES;
    } error:nil];
```

**Comment by codwam** [comment]
SEL sel = NSSelectorFromString(@"dealloc");
    [NSObject aspect_hookSelector:sel withOptions:AspectPositionBefore usingBlock:^(id<AspectInfo> info) {
        
        NSLog(@"hahaha");
        
    } error:NULL];

can it be hook all view controller's dealloc?

**Comment by DamonCode** [comment]
@fatuhoku  you should use  ```
[UIViewController aspect_hookSelector:NSSelectorFromString(@"dealloc") withOptions:AspectPositionBefore
                         usingBlock:^(id<AspectInfo>aspectInfo) {};
```
witout the arg BOOL animated

**Comment by fatuhoku** [comment]
I no longer work on iOS so am happy to close this!
