### ISSUE TITLE
Crashed: com.apple.main-thread EXC_BAD_ACCESS KERN_PROTECTION_FAILURE at 0x0116aebc

### ISSUE THREAD

**Issue by tzq582905** [steipete/Aspects#57]
0	CoreFoundation	
__CFStringAppendBytes + 77
1
CoreFoundation	
__CFStringAppendFormatCore + 7884
2	CoreFoundation	
__CFStringAppendFormatCore + 7884
3
CoreFoundation	
_CFStringCreateWithFormatAndArgumentsAux2 + 80
4
Foundation	
-[NSPlaceholderString initWithFormat:locale:arguments:] + 144
5
Foundation	
-[NSString initWithFormat:arguments:] + 26
6
Foundation	
-[NSString stringByAppendingFormat:] + 92
7
apos	
Aspects.m line 170
aspect_aliasForSelector
8
apos	
Aspects.m line 478
__ASPECTS_ARE_BEING_CALLED__

**Comment by steipete** [comment]
Impossible to debug without explanation text and a sample project.
