### ISSUE TITLE
Does not work with dynamic Swift methods (Swift 2.0)

### ISSUE THREAD

**Issue by serieuxchat** [steipete/Aspects#59]
I have a Swift subclass of UITableViewCell and an @objc method that takes one parameter (NSError).
Hooking this selector gives no errors, but the aspect hook is NOT invoked.
(Xcode 7 beta 6)

**Comment by steipete** [comment]
Haven't tried this with Swift yet - feel free to dig on to see what's up here.

cheers,
Peter

**Comment by serieuxchat** [comment]
Was my fault - I forgot the "dynamic" keyword, and only marked my method as @objc (which was NOT enough!). Duh... :-)

**Comment by serieuxchat** [comment]
Thanks for the awesome library, btw! I am using it in almost every project (for diagnostics logging).

**Comment by steipete** [comment]
Great to hear! Thanks!

**Comment by smitsuchak** [comment]
@serieuxchat Can you please share some snippets of how are you using with Swift and what keywords need to be added ? any limitations ?
