### ISSUE TITLE
UIView subclass hook dealloc cause invocation BAD ACCESS

### ISSUE THREAD

**Issue by saiday** [steipete/Aspects#60]
Using aspects to hook my UIView subclass's `dealloc` method with `AspectPositionBefore` option, it works fine as a before hook, callback get called. 

And it gets BAD ACCESS when Aspects trying to invoke aliasSelector on Line 498:
https://github.com/steipete/Aspects/blob/master/Aspects.m#L498

My question is:
1. Why we need to invoke aliasSelector again when there's no instead hooks?
2. I test on UIViewController subclass and NSObject subclass, they works fine with out BAD ACCESS, do you have any idea why UIView subclass gets BAD ACCESS?

**Comment by saiday** [comment]
Found out that if `baseClass` is `NSKVONotifying_` subclass will cause BAD ACCESS on invocation.

**Comment by steipete** [comment]
Indeed, that made problems before. KVO and Aspects don't always play well.

**Comment by saiday** [comment]
@steipete thank you for awesome Aspects!

https://github.com/steipete/Aspects/blob/master/Aspects.m#L364-L366
I saw you're trying to solve `NSKVONotifying` meta class swizzling.

But I can't figure it out what `aspect_swizzleForwardInvocation` going to do, can you give me some hints?
https://github.com/steipete/Aspects/blob/master/Aspects.m#L391-L399
btw, my `originalImplementation` is NULL inside `aspect_swizzleForwardInvocation` function

**Comment by saiday** [comment]
After reviewing the test cases and source code, I alternatively aspect my `Class` object, skipping KVO object method swizzling part ever since I realized pre-registeded KVO object is currently not support.
I'm trying to contribute, if you do have any hints, please inform me.

All in all, it works now, thank you.
